### ISSUE TITLE
Fix and update "Install Docker on Windows" article?

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-container-service#208] opened 2015-10-15 15:06 UTC
In **/_tutorials/docker-install-windows.md**, the first step in each procedure is run into the intro text. Fix formatting?

Also, **/_references/002-troubleshooting-windos-docker-vm-startup.md** says that existing versions of Git can cause problems when installing Docker Toolbox. We mention existing Oracle VM VirtualBox here, but not Git. Should we?

Should we link to that troublshooting topic from the "Troubleshooting" section if this install article?

**Comment by DonNateR** [comment] 2015-10-15 16:49
@kmsholcomb I don't understand what you mean. The list's in my code and preview are formatted the way they should be. I even compared them to the other installation instructions. Can you show me more specifically what the problem is?

**Comment by kmsholcomb** [comment] 2015-10-15 17:06
The attached screenshot shows what I see when I click the View button. I'm not sure why I see that, because the code does look fine. Maybe it's just a glitch on my system? I guess all that matters is that it looks good in the product UI. 

[screenshot.pdf](https://github.com/rackerlabs/docs-container-service/files/14236/screenshot.pdf)

**Comment by DonNateR** [comment] 2015-10-15 17:20
Alright, tried a couple of things and it looks like whatever I did it fix. @kmsholcomb you can review the PR #209 if you wish. The link is above.

**Comment by kmsholcomb** [comment] 2015-10-15 17:35
@DonNateR: It looks fixed in the first procedure, but not the second one.

**Comment by DonNateR** [comment] 2015-10-19 13:38
Fixed this in second procedure and merged Pr #209. Closing this issue.

**Closed by DonNateR** 2015-10-19 13:38 UTC
